### ISSUE TITLE
operator-linebreak preference

### ISSUE THREAD

**Issue by adamweeks** [ciscospark/web-styleguide#12]
**REALLY** not a fan of the "before" setting of `operator-linebreak`. Highly prefer "after". Thoughts?

```js
// "after" setting
var fullHeight = borderTop +
                 innerHeight +
                 borderBottom;
```
vs
```js
// "before" setting
var fullHeight = borderTop
               + innerHeight
               + borderBottom;
```

https://eslint.org/docs/2.0.0/rules/operator-linebreak

https://github.com/ciscospark/web-styleguide/blob/master/packages/node_modules/%40ciscospark/eslint-config-base/rules/style.js#L379

**Comment by bzang** [comment]
I personally prefer `after` for JSX. I think this is a reasonable change and matches with our `comma` rules. What do others think?

**Comment by andrewholsted** [comment]
> After, after - Mr. Miyagi
