### ISSUE TITLE
Enable no-template-curly-in-string

### ISSUE THREAD

**Issue by ianwremmel** [ciscospark/web-styleguide#14]
https://eslint.org/docs/rules/no-template-curly-in-string

With the switch away from backticks for non-templates, it's easy to create a template string with apostrophes.

**Comment by bzang** [comment]
Good call, seems reasonable

**Comment by ianwremmel** [comment]
@bzang, what file should this change go in?

**Comment by bzang** [comment]
@ianwremmel checking our rules it seems this is already implemented here: https://github.com/ciscospark/web-styleguide/blob/master/packages/node_modules/%40ciscospark/eslint-config-base/rules/errors.js#L96

Is it not working?

**Comment by ianwremmel** [comment]
Hmm. It does seem to be now, but I definitely opened this when it didn't warn me on things last week...

Oh well, closing, I guess.
