### ISSUE TITLE
Purpose of legacy.js eslint?

### ISSUE THREAD

**Issue by adamweeks** [ciscospark/web-styleguide#15]
Does this file serve a purpose? I can't seem to find a reference to it anywhere.

https://github.com/ciscospark/web-styleguide/blob/master/packages/node_modules/%40ciscospark/eslint-config-base/rules/legacy.js

**Comment by bzang** [comment]
@adamweeks, it's a consolidated reference to the old rules. We should be able to get rid of it at this point.
