### ISSUE TITLE
`valid-jsdoc` is actually more helpful if `requireReturn` is set to false

### ISSUE THREAD

**Issue by ianwremmel** [ciscospark/web-styleguide#5]
When we originally set `requireReturn: true`, it was there to ensure that we always documented a return type *when there was one*. A side effect was that it makes you type `@returns {undefined}` a lot. 

Sometime between when we first picked that rule and now, eslint got smarter with `requireReturn: false` such that it still forces you to document `return` if the function returns anything.

**Comment by bzang** [comment]
Gotcha, yea that makes a lot of sense.
